version: '3' # docker-composeのバージョン
services:
  vue:
    build:
      # イメージを作るためのDockerfileがある場所
      context: . # Dockerfileのある場所
      dockerfile: Dockerfile
    container_name: mfe_vue
    volumes:
      # ローカルのデータにコンテナのデータをマウントする。
      - .:/usr/src/app
      - mfe_vue-node_modules:/usr/src/app/front/node_modules
    working_dir: /usr/src/app # デフォルトの作業ディレクトリを指定
    command: sh -c 'cd front && npm run dev'
    environment:
      - CHOKIDAR_USEPOLLING=true # docker環境の中でホットリロードを有効にします。
    tty: true
    stdin_open: true
    ports:
      - "3103:3000" # 左がローカル、右がDocker内のポート
      - "3153:3001"

networks:
  internal:
    driver: bridge
    internal: true
  external:
    external: true
    name: mfe_external

volumes:
  mfe_vue-node_modules: